// FILE: js/04-ui/projection-render.js
// Renders the year-by-year projection table and the year-1 allocator
// suggestions into the DOM. Both renderers are pure: they read the
// engine output and write HTML into known mount points.

function _row(cells, isHeader) {
    const tag = isHeader ? 'th' : 'td';
        return '<tr>' + cells.map(c => '<' + tag + '>' + c + '</' + tag + '>').join('') + '</tr>';
        }

        function renderProjection(result) {
            const mount = document.getElementById('projection-table');
                if (!mount) return;
                    if (!result || !result.years || !result.years.length) {
                            mount.innerHTML = '<p>No projection data.</p>';
                                    return;
                                        }

                                            const header = _row([
                                                    'Year', 'Ordinary', 'ST gain', 'LT gain',
                                                            'Loss generated', 'Fee',
                                                                    'ST loss used', 'LT loss used', 'Ord offset',
                                                                            'ST CF end', 'LT CF end',
                                                                                    'Tax (Brk)', 'Tax (no Brk)', 'Net savings'
                                                                                        ], true);

                                                                                            const body = result.years.map(y => _row([
                                                                                                    y.year,
                                                                                                            fmtUSD(y.ordinary),
                                                                                                                    fmtUSD(y.shortGain),
                                                                                                                            fmtUSD(y.longGain),
                                                                                                                                    fmtUSD(y.grossLoss),
                                                                                                                                            fmtUSD(y.fee),
                                                                                                                                                    fmtUSD(y.shortTermLossUsedAgainstGains),
                                                                                                                                                            fmtUSD(y.longTermLossUsedAgainstGains),
                                                                                                                                                                    fmtUSD(y.ordinaryOffsetUsed),
                                                                                                                                                                            fmtUSD(y.shortCarryforwardEnd),
                                                                                                                                                                                    fmtUSD(y.longCarryforwardEnd),
                                                                                                                                                                                            fmtUSD(y.taxWithBrooklyn),
                                                                                                                                                                                                    fmtUSD(y.taxNoBrooklyn),
                                                                                                                                                                                                            fmtSignedUSD(y.netSavingsThisYear)
                                                                                                                                                                                                                ])).join('');
                                                                                                                                                                                                                
                                                                                                                                                                                                                    const totals = result.totals;
                                                                                                                                                                                                                        const totalsRow =
                                                                                                                                                                                                                                '<tr class="totals"><td colspan="11">Totals</td>' +
                                                                                                                                                                                                                                        '<td colspan="2">Cumulative fees: ' + fmtUSD(totals.cumulativeFees) + '</td>' +
                                                                                                                                                                                                                                                '<td>' + fmtSignedUSD(totals.cumulativeNetSavings) + '</td></tr>' +
                                                                                                                                                                                                                                                        '<tr><td colspan="14" class="cf-final">' +
                                                                                                                                                                                                                                                                'Final ST carryforward: ' + fmtUSD(totals.finalShortCarryforward) +
                                                                                                                                                                                                                                                                        ' &nbsp; Final LT carryforward: ' + fmtUSD(totals.finalLongCarryforward) +
                                                                                                                                                                                                                                                                                '</td></tr>';
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    mount.innerHTML =
                                                                                                                                                                                                                                                                                            '<table class="projection-table">' +
                                                                                                                                                                                                                                                                                                    '<thead>' + header + '</thead>' +
                                                                                                                                                                                                                                                                                                            '<tbody>' + body + totalsRow + '</tbody>' +
                                                                                                                                                                                                                                                                                                                    '</table>';
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    function renderAllocator(allocation) {
                                                                                                                                                                                                                                                                                                                        const mount = document.getElementById('allocator-output');
                                                                                                                                                                                                                                                                                                                            if (!mount) return;
                                                                                                                                                                                                                                                                                                                                if (!allocation || !allocation.best) {
                                                                                                                                                                                                                                                                                                                                        mount.innerHTML = '<p>No viable Brooklyn allocation for the supplied capital and minimums.</p>';
                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                        const b = allocation.best;
                                                                                                                                                                                                                                                                                                                                                            const top = '<div class="best">' +
                                                                                                                                                                                                                                                                                                                                                                    '<h3>Suggested year-1 allocation</h3>' +
                                                                                                                                                                                                                                                                                                                                                                            '<dl>' +
                                                                                                                                                                                                                                                                                                                                                                                    '<dt>Tier</dt><dd>' + b.tierKey + '</dd>' +
                                                                                                                                                                                                                                                                                                                                                                                            '<dt>Leverage</dt><dd>' + b.leverage + 'x</dd>' +
                                                                                                                                                                                                                                                                                                                                                                                                    '<dt>Investment</dt><dd>' + fmtUSD(b.investment) + '</dd>' +
                                                                                                                                                                                                                                                                                                                                                                                                            '<dt>Gross loss generated</dt><dd>' + fmtUSD(b.grossLoss) + '</dd>' +
                                                                                                                                                                                                                                                                                                                                                                                                                    '<dt>Fee</dt><dd>' + fmtUSD(b.fee) + '</dd>' +
                                                                                                                                                                                                                                                                                                                                                                                                                            '<dt>Net year-1 savings</dt><dd>' + fmtSignedUSD(b.netSavings) + '</dd>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                    '<dt>Carryforward (after year 1)</dt><dd>' + fmtUSD(b.carryforwardLeft) + '</dd>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                            '</dl></div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                const altRows = (allocation.candidates || []).slice(0, 8).map(c =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        _row([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c.tierKey, c.leverage + 'x',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fmtUSD(c.investment),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fmtUSD(c.grossLoss), fmtUSD(c.fee),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fmtSignedUSD(c.netSavings)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const altTable =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '<h4>Top alternatives</h4>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<table class="allocator-alts">' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '<thead>' + _row(['Tier','Lev','Investment','Gross loss','Fee','Net y1 savings'], true) + '</thead>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<tbody>' + altRows + '</tbody>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '</table>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mount.innerHTML = top + altTable;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
